FROM registry.redhat.io/devspaces/udi-rhel8:latest

USER root

RUN \
    # install all the rpms and modules
    microdnf install -y dnf && \
    dnf -y -q install --setopt=tsflags=nodocs \
        rsync \
    && \
    dnf -y -q clean all --enablerepo='*' && \
    dnf -y -q clean all && rm -rf /var/cache/yum

RUN rm ${HOME}/.java/current/* && ln -s /usr/lib/jvm/java-17-openjdk/* ${HOME}/.java/current
RUN dnf install -y maven-openjdk17 --allowerasing

ENTRYPOINT [ "/entrypoint.sh" ]
WORKDIR /projects
CMD tail -f /dev/null
