kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "fruit-gateway.fullname" . }}
  labels:
    {{- include "fruit-gateway.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: fruit-gateway
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
