---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fruit-gateway.genericWebhookSecret" . }}
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "fruit-gateway.genericWebhookSecret" .) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $WebHookSecretKey := (get $secretData "WebHookSecretKey") | default (randAlphaNum 32 | b64enc) }}
  WebHookSecretKey: {{ $WebHookSecretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fruit-gateway.githubWebhookSecret" . }}
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "fruit-gateway.githubWebhookSecret" .) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $WebHookSecretKey := (get $secretData "WebHookSecretKey") | default (randAlphaNum 32 | b64enc) }}
  WebHookSecretKey: {{ $WebHookSecretKey | quote }}