#!/bin/sh

CURRENT_DIR=$(pwd)
cd $(dirname $0)

. ./image-env.sh

podman tag ${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH}
podman tag ${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${ARTIFACT_VERSION}

podman push $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH}
podman push $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${ARTIFACT_VERSION}

cd ${CURRENT_DIR}