kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"events-database:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"events-database\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  name: {{ include "fruit-service-db.fullname" . }}
  labels:
    {{- include "fruit-service-db.labels" . | nindent 4 }}
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fruit-service-db.selectorLabels" . | nindent 6 }}
      # deployment: {{ include "fruit-service-db.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "fruit-service-db.selectorLabels" . | nindent 8 }}
        # deployment: {{ include "fruit-service-db.fullname" . }}
    spec:
      containers:
        - name: database
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.dataBaseImage }}
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "fruit-service-db.fullname" . }}-secret
                  key: DB_NAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fruit-service-db.fullname" . }}-secret
                  key: DB_PASSWORD
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "fruit-service-db.fullname" . }}-secret
                  key: DB_USER
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 150Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600