apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fruit-service-db-secret" . }}
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "fruit-service-db-secret" .) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $DB_USER := (get $secretData "DB_USER") | default (randAlphaNum 32 | b64enc) }}
  {{- $DB_PASSWORD := (get $secretData "DB_PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  {{- $DB_NAME := ("FRUITSDB" | b64enc) }}
  DB_USER: {{ $DB_USER | quote }}
  DB_PASSWORD: {{ $DB_PASSWORD | quote }}
  DB_NAME: {{ $DB_NAME | quote }}