apiVersion: v1
kind: Service
metadata:
  name: {{ include "fruit-service-db.fullname" . }}
  labels:
    {{- include "fruit-service-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "fruit-service-db.selectorLabels" . | nindent 4 }}
